<?php
    //Autor: Vinícius Lessa - 05/06/2019
    //Obs.: Essa função será chamada em toda página do portal, trazendo como parâmetro o Idioma escolhido
    //pelo usuários. Esse valor será capiturado através do Método 'POST' na própria página.
    function Translate($message) {
        //Se PORTUGUÊS (Obs.: NÃO É DEFAULT, pois deverá ser setado no BUTTON de seleção de idioma)
        $messages = array(
          // Menus
          'FEED MUSICAL' =>  'MUSIC FEED',
          'MUSIC TRADE CENTER' =>  'MUSIC TRADE CENTER',
          'ANUNCIAR' =>  'ANUNCIATE',
        'Melhores - Rankging' => 'The Best - Ranking',
        'Saiba Mais' => 'Learn More',
        'LANÇAMENTOS MAIS ESPERADOS' => 'MORE EXPECTED LAUNCHES',
        'Conferência Completa e Novidades na E3 2019: Microsoft' =>'Full Conference and News at E3 2019: Microsoft',
        'Páginas Relacionadas' => 'Related Pages',
        'Novos Trailers Espetaculares' => 'New Spectacular Trailers',
        'Sony Traz Novidades' => 'Sony Brings News',
        'Mercado de Games Cresce' => 'Games Market Grows',
        'Notícias Que Podem lhe Interessar' => 'News That May Interest You',
        'Novos Trailers do game dos Vingadores' =>'New Avengers Game Trailers',
        'Fifa 2020 Traz Novidades' =>'Fifa 2020 Brings Whats New',
        'Borderlands 3 Anunciado' => 'Borderlands 3 Announced',
        'O melhor conteúdo Gamer da WEB'  => 'The best Gamer content in the WEB',
        'Saiba mais' => 'Read more',
        'Jogos Online: PC' => 'Online Games: PC',
        'Lançamentos Mobile' => 'Mobile Releases',
        'O melhor conteúdo Gamer da WEB'  => 'The best Gamer content in the WEB',
        'Saiba mais' => 'Read more',
        'Jogos Online: PC' => 'Online Games: PC',
        'Lançamentos Mobile' => 'Mobile Releases',
        'História: Video-games'  => 'History: Video-games',
        'Era 80/90' => 'Era 80/90',
        'Sobre' => 'About',
        'Simuladores' => 'Simulators',
        'Clássicos do Mundo Gamer' => 'Classics of the Gamer World',
        'Sobre os Nossos Clássicos Preferidos' => 'About Our Favorite Classics',
        'Clássicos' => 'Classics',
        'GAMES MARCANTES DESSE SÉCULO' => 'BEST GAMES OF THE CENTURY',
        'CLÁSSICOS' => 'CLASSIC GAMES',
        'PC'  => 'PC',
        'JOGOS'  => 'GAMES',
        'SIMULADORES' => 'SIMULATORS',
        'LANÇAMENTOS' => 'RELEASES',
        'Lançamentos' => 'Releases',
        'Portáteis'  => 'Handheld Consoles',
        'Os mais jogados'  => 'Most played',
        'MOBILE' => 'MOBILE',
        'Mobile' => 'Mobile',
        'MELHORES DO SÉCULO'  => 'BEST OF THE CENTURY',
        'Melhores do Século'  => 'Best of the Century',
        'VIDEOGAMES' => 'VIDEOGAMES',
        'Videogames' => 'Videogames',
        'DESENVOLVEDORAS' => 'DEVELOPERS',
        'Desenvolvedoras' => 'Developers',
        'OUTROS'  => 'OTHER',
        'CONTATOS'  => 'CONTACT US',
        'Contatos'  => 'Contact us',
        'QUEM SOMOS'  => 'WHO WE ARE',
        'Quem Somos'  => 'Who we are',
        'SOBRE NÓS'  => 'ABOUT US',
        'CRIAR CONTA' => 'SIGN UP',
        'Criar conta' => 'Sign up',
        'MAPA DO SITE' => 'SITEMAP',
        'Página Inicial' => 'Home',
        'Deixe sua opinião!' => 'Give us your feedback!',
        'NORMAS DE UTILIZAÇÃO'  => 'TERMS OF USE',
        'Normas de Utilização'  => 'Terms of Use',
        'ESTRUTURA ORIGIAL DO SITE' => 'WEBSITE ORIGINAL STRUCTURE',
        'ÚLTIMAS NOVIDADES' => 'LATEST NEWS',
        'OS JOGOS QUE MARCARAM ÉPOCA' => 'MOST IMPORTANT GAMES',
        'ARTIGOS RELACIONADOS'  => 'RELATED ARTICLES',
        'TOP 10 MOBILE' => 'TOP 10 MOBILE',
        'HISTÓRIA DOS PORTÁTEIS'  => 'HANDHELD CONSOLES HISTORY',
        'OS MAIS JOGADOS' => 'THE MOST PLAYED',
        'Os jogos mais populares para mobile do mundo.'           => 'The worlds most popular mobile games.',
        'A EVOLUÇÃO DOS PORTÁTEIS'  => 'HANDHELD CONSOLES EVOLUTION',
        'Os games mais esperados para mobile - ação, corrida, estratégia e mais!'           => 'The most anticipated mobile games - action, racing, strategy and more!',
        'O avanço tecnológico dos videogames portáteis ao longo das ultimas décadas.'           => 'The tecnological advance of handheld consoles in the last decades',
        'FALE CONOSCO'  => 'LEAVE A MESSAGE',
        'TELEFONE'  => 'PHONE',
        'DESENVOLVEDORES FAMOSOS' => 'FAMOUS DEVELOPERS',
        'COMO SER UM DESENVOLVEDOR' => 'HOW TO BECOME A DEVELOPER',
        'DESENVOLVEDORES DE GAMES'  => 'GAME DEVELOPERS',
        'APRENDA A SER UM DESENVOLVEDOR DE GAMES'           => 'LEARN HOW TO BE A GAME DEVELOPER',
        'Jogos do Século XXI' => 'Games of the XXI century',
        'Ano Vencedor:' => 'Year awarded:',
        'Prêmio - Jogos do Ano' => 'Awards - Game of the Year',
        'Vencedores do prêmio de JOGO DO ANO' => 'GAME OF THE YEAR WINNERS',
        'Prêmios - Jogos do Ano' => 'Game of the Year Award',
        'Fonte' => 'Source',
        'O que é o Prêmio de Jogo do Ano?'  => 'What is the Game of the Year Awards?',
        'Melhores Games do Século XXI'  => 'Best games of the XXI century',
        'Hitória dos jogos para pc' => 'PC games history',
        'Tipos de computadores' => 'Types of computers',
        'Diferenças entre pc gamer e videogames'  => 'Difference between gamer PCs and consoles',
        'Hardware, especificações e inovações'  => 'Hardware, specifications and innovation',
        'Diferença entre PC GAMER de alto custo e um de baixo custo'  => 'Difference between high end gamer PC and low budget',
        'Momento de diversão, jogue o clássico PRINCE OF PERSIA!' => 'Time for fun, play the classic PRINCE OF PERSIA!',
        'Momento de diversão, jogue o clássico DOOM!' => 'Time for fun, play the classic DOOM!',
        'Momento de diversão, jogue o clássico RAPTOR!' => 'Time for fun, play the classic RAPTOR!',
        'Conheça a história dos jogos para PC e suas evoluções' => 'Learn about the PC games history and their evolution',
        'Conheça o universo dos jogos On-line para PC'  => 'Learn about the On-line PC gaming',
        'Jogos exclusivos para pc'  => 'PC exclusive games',
        'Evolução dos jogos para pc'  => 'PC games evolution',
        'Ascenção dos jogos online para PC' => 'Online PC games rise',
        'Principais campeonatos e seus premios' => 'Most important championships and awards',
        'Modalidades e principais jogadores'  => 'Categories and best players',
        'MELHORES JOGADORES E-SPORTS DO BRASIL' => 'BEST BRAZILIAN E-SPORTS PLAYERS',
        'Assista uma partida online'  => 'Watch a live match',
        'Melhores jogos para Pc da Atualidade'  => 'Best games for PC nowadays',
        'Conheça o universo dos jogos On-line para PC'  => 'Know more about the On-line games universe',
        'Tudo o que rola no fantástico mundo dos PC Games'  => 'Everithing thats going on in the fantastic world of PC Games',
        'TOP FIVE: Os games que marcaram época' => 'TOP FIVE: Games that marked its time',
        'O que há para ver?'  => 'What is there to see?',
        'VEJA TAMBÉM' => 'SEE ALSO',
        'PRÊMIO DE MELHORES JOGOS DO ANO' => 'BEST OF THE YEAR AWARDS',
        'E-MAIL'  => 'E-MAIL',
        'OS MELHORES JOGOS CLÁSSICOS' => 'THE BEST CLASSIC GAMES',
        'LANÇAMENTOS MAIS ESPERADOS' => 'MOST AWAITED RELEASES',
        'Conferência Completa e Novidades na E3 2019: Microsoft' => 'E3 Full Conference and News: Microsoft',
        'Talvez Você Goste' => 'Maybe You Like',
        'Novos Trailers Irados' => 'New Cool Trailers',
        'Consoles da Nova Geração - Xbox e PS5' => 'New Generation Consoles - Xbox and PS5',
        'Relembre a Geração 2000' => 'Remember 2000s Generation',
        'Inspire-se Com o Spider Man' => 'Get Inspired With The Spider Man',
        'Melhores Games do Século' => 'Best Games of Century',
        'Desenvolvimento de Games' => 'Game Development',
        'Novidades Sobre PCs' => 'News About PCs',
        'Novidades Que Podem Lhe Interessar' => 'News That May Interest You',
        'Fique por Dentro de Todos os Trailers da E3' => 'See All E3 Trailers',
        'A Volta do Capitão' => 'The Captains Return',
        'Conferência da E3' => 'E3 Conference',
        'Jogos Clássicos' => 'Classic Games',
        'JOGOS CLÁSSICOS' => 'CLASSIC GAMES',
        'Tecnologia VR' => 'VR Tecnology',
        'Conheça os Clássicos' => 'Meet the Classics',
        'Principais Clássicos' => 'Main Classics',
        'VR Chegou Para Ficar' => 'VR Arrived to Stay',
        'Aprenda a Criar Games' => 'Learn to Create Games',
        'CLÁSSICOS QUE AINDA PODEMOS JOGAR' => 'CLASSICS WE CAN STILL PLAY',
        'OS PRINCIPAIS JOGOS CLÁSSICOS' => 'THE MAIN CLASSIC GAMES',
        'Ler Mais' => 'Read About It',
        'Conheça as Especificações e Poder dos Novos Consoles' => 'Meet the Specifications and Power of The New Consoles',
        'Configurações Xbox x PS4 - Antiga e Nova Geração' => 'Settings Xbox x PS4 - Old and New Generation',
        'Curiosidades da Antiga Geração' => 'Curiosities of the Old Generation',
        'CURIOSIDADES' => 'CURIOSITIES',
        'Curiosidades' => 'Curiosity',
        'O jogo mais vendido da história por 22 anos' => 'The best-selling game in history for 22 years',
        'Os velhinhos que ainda fazem bastante sucesso' => 'The old games that still make a success',
        'Do arcade para os jogos eletronicos' => 'From the arcade games to the electronic games',
        'Curiosidades dos Clássicos' => 'Curiosity of the Classics',
        'CURIOSIDADE DOS CLÁSSICOS' => 'CURIOSITY OF THE CLASSICS',
        'O Primeiro Jogo Competitivo' => 'The First Competitive Game',
        'O PRIMEIRO JOGO ELETRONICO COMPETITIVO' => 'THE FIRST COMPETITIVE ELECTRONIC GAME',
        'Moedas e Mais Moedas' => 'Coins and More Coins',
        'Voltar' => 'Back',
        'Voltar ao início' => 'Back to top',
        'PULAR PARA CONTEÚDO PRINCIPAL' => 'SKIP TO MAIN CONTENT',
        'Rodapé da página' => 'Page footer',
        'LISTA DOS MELHORES' => 'LIST OF THE BEST',
        'MELHORES XXI' => 'BEST XXI',
        'JOGO' => 'GAME',
        'ANO' => 'YEAR',
        'JOGOS QUE FORAM RAMASTERIZADOS' => 'GAMES THAT WERE REMASTERED',
        'ACESSE TAMBÉM' => 'SEE ALSO',
        'Pizza e Jogos' => 'Pizza and Games'
      );

        if (!empty($_SESSION['lang'])){
          if ($_SESSION['lang'] == 'pt-BR') {
            return $message;
          } elseif ($_SESSION['lang'] == 'en') {
            return $messages[$message];
          }
        } else{
          return $message;
        }
        
}
?>